// LocaleContext.tsx — GENERATED by `brotea new` / `brotea i18n sync` from
// i18n/runtime/LocaleContext.tsx. Fix it in the factory, not here.
//
// The `react` stack shares one locale across the whole SPA: <LocaleProvider>
// wraps the app, any component (including feature bricks) calls useI18n().
// In the `astro` stack the server already knows the locale — pass it to
// islands as a prop instead of reaching for this.
import { createContext, useContext, type ReactNode } from 'react';
import { DEFAULT_LOCALE, LOCALES, tt, type Locale, type Vars } from './i18n';
import { useLocale } from './useLocale';

type I18n = {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string, vars?: Vars) => string;
  locales: Locale[];
};

const Ctx = createContext<I18n>({
  locale: DEFAULT_LOCALE,
  setLocale: () => {},
  t: tt(DEFAULT_LOCALE),
  locales: LOCALES,
});

export function LocaleProvider({ children }: { children: ReactNode }) {
  return <Ctx.Provider value={useLocale()}>{children}</Ctx.Provider>;
}

export const useI18n = () => useContext(Ctx);
