// GENERATED by scripts/gen-model.mjs from pb/schema.json — do not edit.
//
// The database enforces these shapes; this file is how the UI knows them.
// Editing it by hand puts the two back out of step, which is the problem it
// exists to solve. Change pb/schema.json and regenerate.

export interface Users {
  id: string;
}
