// useLocale.ts — GENERATED by `brotea new` / `brotea i18n sync` from
// i18n/runtime/useLocale.ts. Fix it in the factory, not here.
//
// For the `react` stack (a client-rendered SPA: no URL prefix, the choice is
// the user's and it persists). In the `astro` stack the locale is known on the
// server and must be passed to React islands as a prop instead — that is what
// keeps the HTML crawlable.
import { useEffect, useState } from 'react';
import { DEFAULT_LOCALE, LOCALES, dirOf, isLocale, tt, type Locale, type Vars } from './i18n';

const KEY = 'brotea.locale';

// Runs during render, so it must survive SSR (Astro islands are prerendered).
function initialLocale(): Locale {
  if (typeof window === 'undefined') return DEFAULT_LOCALE;
  const saved = window.localStorage.getItem(KEY);
  if (isLocale(saved)) return saved;
  const fromBrowser = (navigator.languages ?? [navigator.language])
    .map((l) => l.split('-')[0])
    .find(isLocale);
  return fromBrowser ?? DEFAULT_LOCALE;
}

export function useLocale(): {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string, vars?: Vars) => string;
  locales: Locale[];
} {
  const [locale, setLocale] = useState<Locale>(initialLocale);
  useEffect(() => {
    window.localStorage.setItem(KEY, locale);
    document.documentElement.lang = locale;
    document.documentElement.dir = dirOf(locale); // rtl languages need this
  }, [locale]);
  return { locale, setLocale, t: tt(locale), locales: LOCALES };
}
