// LanguageSwitcher.tsx — GENERATED by `brotea new` / `brotea i18n sync` from
// i18n/runtime/LanguageSwitcher.tsx. Fix it in the factory, not here.
//
// The `react` stack switcher: a <select>, because a SPA nav is tight on space
// and a native select is the accessible, zero-CSS option on mobile.
import { NATIVE, type Locale } from '../lib/i18n';

export default function LanguageSwitcher(
  { locale, locales, onChange, label }:
  { locale: Locale; locales: Locale[]; onChange: (l: Locale) => void; label: string },
) {
  return (
    <label style={{ display: 'flex', gap: 'var(--space-2)', alignItems: 'center', fontSize: '0.9rem' }}>
      <span className="sr-only" style={{ color: 'var(--muted)' }}>{label}</span>
      <select
        value={locale}
        onChange={(e) => onChange(e.target.value)}
        aria-label={label}
        style={{
          font: 'inherit',
          color: 'var(--text)',
          background: 'var(--bg)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius)',
          padding: '0.25rem 0.4rem',
        }}
      >
        {locales.map((code) => (
          <option key={code} value={code}>{NATIVE[code]}</option>
        ))}
      </select>
    </label>
  );
}
